-- MySQL Script generated by MySQL Workbench
-- Tue Jun 15 10:22:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dominican
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `civilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civilite` ;

CREATE TABLE IF NOT EXISTS `civilite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `etat_civil` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `civilite` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `demande_billet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demande_billet` ;

CREATE TABLE IF NOT EXISTS `demande_billet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accept_condition_generale` TINYINT(1) NULL,
  `demande_immediat` TINYINT(1) NULL,
  `apport_bagage` ENUM('Oui', 'Non') NOT NULL,
  `apport_nourriture` ENUM('Oui', 'Non') NOT NULL,
  `apport_marchandise_taxable` ENUM('Oui', 'Non') NOT NULL,
  `passager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_demande_billet_passager`
    FOREIGN KEY (`passager_id`)
    REFERENCES `passager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `demande_billet` (`id` ASC) VISIBLE;

CREATE INDEX `fk_demande_billet_passager_idx` ON `demande_billet` (`passager_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `information_adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_adresse` ;

CREATE TABLE IF NOT EXISTS `information_adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresse_permanent` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `etat` VARCHAR(255) NOT NULL,
  `code_postal` INT NOT NULL,
  `type_voyage` ENUM('arrivée', 'depart') NULL,
  `is_arret_frequent` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `information_adresse` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `passager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passager` ;

CREATE TABLE IF NOT EXISTS `passager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `noms` VARCHAR(255) NOT NULL,
  `nom_famille` VARCHAR(255) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `genre` ENUM('masculin', 'feminin', 'autre') NOT NULL,
  `pays_naissance` VARCHAR(255) NOT NULL,
  `pays_nationnalite` VARCHAR(255) NOT NULL,
  `numero_passport` VARCHAR(255) NOT NULL,
  `accept_sejour_hotel` TINYINT(1) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  `civilite_id` INT NOT NULL,
  `information_adresse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_passager_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passager_civilite1`
    FOREIGN KEY (`civilite_id`)
    REFERENCES `civilite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passager_information_adresse1`
    FOREIGN KEY (`information_adresse_id`)
    REFERENCES `information_adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `passager` (`id` ASC) VISIBLE;

CREATE INDEX `fk_passager_profession1_idx` ON `passager` (`profession_id` ASC) VISIBLE;

CREATE INDEX `fk_passager_civilite1_idx` ON `passager` (`civilite_id` ASC) VISIBLE;

CREATE INDEX `fk_passager_information_adresse1_idx` ON `passager` (`information_adresse_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `profession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profession` ;

CREATE TABLE IF NOT EXISTS `profession` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `profession` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `symptome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symptome` ;

CREATE TABLE IF NOT EXISTS `symptome` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `symptome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `symptome` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `symptome_has_passager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symptome_has_passager` ;

CREATE TABLE IF NOT EXISTS `symptome_has_passager` (
  `symptome_id` INT NOT NULL,
  `passager_id` INT NOT NULL,
  PRIMARY KEY (`symptome_id`, `passager_id`),
  CONSTRAINT `fk_symptome_has_passager_symptome1`
    FOREIGN KEY (`symptome_id`)
    REFERENCES `symptome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_symptome_has_passager_passager1`
    FOREIGN KEY (`passager_id`)
    REFERENCES `passager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_symptome_has_passager_passager1_idx` ON `symptome_has_passager` (`passager_id` ASC) VISIBLE;

CREATE INDEX `fk_symptome_has_passager_symptome1_idx` ON `symptome_has_passager` (`symptome_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
